//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace CUbaBuscaApp
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<CbteTipo>();
                db.CreateTable<Clientes>();
                db.CreateTable<ConceptoTipo>();
                db.CreateTable<Configuraciones>();
                db.CreateTable<DocTipo>();
                db.CreateTable<EstadoFactura>();
                db.CreateTable<Factura>();
                db.CreateTable<facturacionRapidaconf>();
                db.CreateTable<FacturaDetalles>();
                db.CreateTable<formaspago>();
                db.CreateTable<Inversocomprob>();
                db.CreateTable<IvaTipo>();
                db.CreateTable<Logininfo>();
                db.CreateTable<Moneda>();
                db.CreateTable<Precio>();
                db.CreateTable<PtoVenta>();
                db.CreateTable<Responsabilidades>();
                db.CreateTable<Servicio>();
                db.CreateTable<usuario>();
            }
        }
    }
    public partial class CbteTipo
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String Desc { get; set; }
        
        public String FchDesde { get; set; }
        
        public String FchHasta { get; set; }
        
    }
    
    public partial class Clientes
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String Nombre { get; set; }
        
        public Int64? idtipoDoc { get; set; }
        
        public String conceptiva { get; set; }
        
        [NotNull]
        public Int64 nrodoc { get; set; }
        
        public String desctipodoc { get; set; }
        
        public String docmicilio { get; set; }
        
    }
    
    public partial class ConceptoTipo
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String Desc { get; set; }
        
        public String FchDesde { get; set; }
        
        public String FchHasta { get; set; }
        
    }
    
    public partial class Configuraciones
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String clave { get; set; }
        
        [NotNull]
        public String valor { get; set; }
        
        public String descripcion { get; set; }
        
    }
    
    public partial class DocTipo
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String Desc { get; set; }
        
        public String FchDesde { get; set; }
        
        public String FchHasta { get; set; }
        
    }
    
    public partial class EstadoFactura
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        [NotNull]
        public String descripcion { get; set; }
        
    }
    
    public partial class Factura
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public DateTime fechacreacion { get; set; }
        
        [NotNull]
        public Double total { get; set; }
        
        public String nombrecliente { get; set; }
        
        [NotNull]
        public String letrafact { get; set; }
        
        [NotNull]
        public Int64 estadoId { get; set; }
        
        [NotNull]
        public String monedaId { get; set; }
        
        public String monedadesc { get; set; }
        
        public Int64? numeroFact { get; set; }
        
        public Int64? conceptoId { get; set; }
        
        public Int64? clientdId { get; set; }
        
        public Int64? cbteId { get; set; }
        
        public String estadoEnvioAfiperror { get; set; }
        
        public String cae { get; set; }
        
        public Double? noGravado { get; set; }
        
        public String estadodesc { get; set; }
        
        public Int64? ptovta { get; set; }
        
        public Int64? originalidfact { get; set; }
        
        public String NroRef { get; set; }
        
        [NotNull]
        public DateTime fechafacturacion { get; set; }
        
        public Int64? formapagoId { get; set; }
        
    }
    
    public partial class facturacionRapidaconf
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public Int64? servicioId { get; set; }
        
        public Int64? percioId { get; set; }
        
        public String preciodesc { get; set; }
        
        public Int64? cantidad { get; set; }
        
        public Double? total { get; set; }
        
        public String frdesc { get; set; }
        
        public Double? porciva { get; set; }
        
        public Double? ivavalue { get; set; }
        
        public Int64? ivaId { get; set; }
        
        public Double? precio { get; set; }
        
        public Int64? cbteid { get; set; }
        
        public String letraFact { get; set; }
        
        public Int64? conceptoid { get; set; }
        
        public String conceptoDesc { get; set; }
        
        public Int64? ptovta { get; set; }
        
    }
    
    public partial class FacturaDetalles
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public Int64? precioId { get; set; }
        
        public Double? precio { get; set; }
        
        public Int64? cantidad { get; set; }
        
        public Int64? impuestoId { get; set; }
        
        public Double? impuestovalor { get; set; }
        
        public Double? total { get; set; }
        
        public String monedaId { get; set; }
        
        public Int64? facturaId { get; set; }
        
        public String monedadesc { get; set; }
        
        public Double? impuestobase { get; set; }
        
        public String preciodesc { get; set; }
        
        public String serviciodesc { get; set; }
        
    }
    
    public partial class formaspago
    {
        public Int64? id { get; set; }
        
        public String descripcion { get; set; }
        
    }
    
    public partial class Inversocomprob
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public Int64? idcomprob { get; set; }
        
        public Int64? idinverso { get; set; }
        
    }
    
    public partial class IvaTipo
    {
        [PrimaryKey]
        public String Id { get; set; }
        
        public String Desc { get; set; }
        
        public String FchDesde { get; set; }
        
        public String FchHasta { get; set; }
        
    }
    
    public partial class Logininfo
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String uniqueId { get; set; }
        
        [NotNull]
        public DateTime generationTime { get; set; }
        
        [NotNull]
        public DateTime expirationTime { get; set; }
        
        [NotNull]
        public String sign { get; set; }
        
        [NotNull]
        public String token { get; set; }
        
    }
    
    public partial class Moneda
    {
        [PrimaryKey]
        public String Id { get; set; }
        
        public String Desc { get; set; }
        
        public String FchDesde { get; set; }
        
        public String FchHasta { get; set; }
        
    }
    
    public partial class Precio
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public Int64 ServicioId { get; set; }
        
        [NotNull]
        public Double precio { get; set; }
        
        [NotNull]
        public DateTime vigenciaDesde { get; set; }
        
        [NotNull]
        public DateTime vigenciaHasta { get; set; }
        
        public String descripcion { get; set; }
        
        public Int64? ivaId { get; set; }
        
        public Double? ivamonto { get; set; }
        
    }
    
    public partial class PtoVenta
    {
        public Int64? Nro { get; set; }
        
        public String EmisionTipo { get; set; }
        
        public String Bloqueado { get; set; }
        
        public String FchBaja { get; set; }
        
    }
    
    public partial class Responsabilidades
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        [NotNull]
        public String responsabilidad { get; set; }
        
    }
    
    public partial class Servicio
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [Unique(Name = "Servicio_nombre", Order = 0)]
        [NotNull]
        public String nombre { get; set; }
        
    }
    
    public partial class usuario
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String nombre { get; set; }
        
        [NotNull]
        public String email { get; set; }
        
    }
    
}
