//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace Afip
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Factura>();
                db.CreateTable<Precio>();
                db.CreateTable<Servicio>();
                db.CreateTable<usuario>();
            }
        }
    }
    public partial class Factura
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public DateTime fechacreacion { get; set; }
        
        [NotNull]
        public Byte[] servicioId { get; set; }
        
        [NotNull]
        public Decimal cantidad { get; set; }
        
        [NotNull]
        public Decimal precio { get; set; }
        
        [NotNull]
        public Decimal total { get; set; }
        
        [NotNull]
        public String nombrecliente { get; set; }
        
        [NotNull]
        public String letrafact { get; set; }
        
    }
    
    public partial class Precio
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public Int64 ServicioId { get; set; }
        
        [NotNull]
        public Decimal precio { get; set; }
        
        [NotNull]
        public DateTime vigenciaDesde { get; set; }
        
        [NotNull]
        public DateTime vigenciaHasta { get; set; }
        
    }
    
    public partial class Servicio
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String nombre { get; set; }
        
    }
    
    public partial class usuario
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String nombre { get; set; }
        
        [NotNull]
        public String email { get; set; }
        
    }
    
}
